### ISSUE TITLE
documentation and outputs diffrent from example.sh script

### ISSUE THREAD

**Issue by ajaybhatnagar** [floragunncom/search-guard-ssl-docs#6]
Executing example.sh produces following files:
 as against documentation specific:
    node-0-keystore.jks
    node-1-keystore.jks
    node-2-keystore.jks
Which files are to be associated with which node is not clear because of different output.

root@es-tst-c01:/var/tmp/search-guard-ssl/example-pki-scripts# ls -1
ca
certs
clean.sh
crl
etc
example.sh
gen_client_node_cert.sh
gen_node_cert.sh
gen_root_ca.sh
kirk.crt.pem
kirk.csr
kirk.key.pem
kirk-keystore.jks
kirk-keystore.p12
kirk-signed.pem
spock.crt.pem
spock.csr
spock.key.pem
spock-keystore.jks
spock-keystore.p12
spock-signed.pem
truststore.jks

**Comment by floragunncom** [comment]
Hi and thanks for your input. Which version of SG SSL do you use? I just cloned master and executed the example.sh script, and for me the files are generated as per docs:

ca/
certs/
clean.sh*
crl/
etc/
example.sh*
gen_client_node_cert.sh*
gen_node_cert.sh*
gen_root_ca.sh*
kirk-keystore.jks
kirk-keystore.p12
kirk-signed.pem
kirk.crt.pem
kirk.csr
kirk.key.pem
node-0-keystore.jks
node-0-keystore.p12
node-0-signed.pem
node-0.csr
node-1-keystore.jks
node-1-keystore.p12
node-1-signed.pem
node-1.csr
node-2-keystore.jks
node-2-keystore.p12
node-2-signed.pem
node-2.csr
spock-keystore.jks
spock-keystore.p12
spock-signed.pem
spock.crt.pem
spock.csr
spock.key.pem
truststore.jks

**Comment by ajaybhatnagar** [comment]
Thanks for prompt reply. After looking into the scripts, it turns out that keytool of JVM was not in the path. It was not giving any error in first pass but continues execution with out generating the node files. Script should abort if a particular required program is not found.

After replacing keytool command with full path , node files are generated.

Suggestion, it should take number of nodes as command line argument so that files can be generated for all nodes of the cluster.

Thanks
Ajay

**Comment by ajaybhatnagar** [comment]
After generating the files and deploying, starting elasticsearch results in following errors:
Elasticsearch version is 2.3.3 and searchguard plugin versions are:
search-guard-ssl/2.3.3.13
search-guard-2/2.3.3.2

Error on startup of ES: 
[2016-07-05 18:38:10,212][ERROR][bootstrap                ] Exception
ElasticsearchSecurityException[java.io.IOException: Invalid keystore format]; nested: IOException[Invalid keystore format];
        at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:261)
        at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:139)
        at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
        at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:127)
        at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:263)
        at org.elasticsearch.node.Node.<init>(Node.java:179)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:208)

Files in config directory of one of the node are:
root@es-tst-m01:/es1/etc/elasticsearch# ls -l
total 28
-rw-r--r-- 1 elasticsearch elasticsearch 1913 Jul  5 18:27 elasticsearch.yml
-rw-r--r-- 1 elasticsearch elasticsearch 2794 Jul  5 18:23 kibana.yml
-rw-r--r-- 1 elasticsearch elasticsearch 1143 Jul  5 18:23 logging.yml
-rw-r--r-- 1 elasticsearch elasticsearch 7145 Jul  5 18:26 node-0-keystore.jks
drwxr-xr-x 2 elasticsearch elasticsearch 4096 Jul  5 18:23 scripts
-rw-r--r-- 1 elasticsearch elasticsearch 1635 Jul  5 18:26 truststore.jks

**Comment by floragunncom** [comment]
Yes, specifying the number of certificates you want to create on the command line is a good idea. Will add this as feature request to our backlog, thanks!

Regarding the exception: Make sure that you set the type of the keystore correctly. The config key for this is:

searchguard.ssl.transport.keystore_type: (PKCS12/JKS)
"The type of the keystore file, JKS or PKCS12 (Optional, default: JKS)"

Make sure it is not set the PKCS12, or set it directly to JKS. Please also post your elasticsearch.yml containing all the SG related settings, so we can investigate further.

**Comment by ajaybhatnagar** [comment]
Here is full Elasticsearch.yml file including searchguard settings. I am relying on default JKS keystore hence that setting not set.
Thank
Ajay

cluster.name: ESTEST-ANS
node.name: es-tst-m01
path.conf: /es1/etc/elasticsearch
path.data: /es1/data/elasticsearch
path.work: /tmp
path.logs: /es1/logs/elasticsearch
path.plugins: /usr/share/elasticsearch/plugins
bootstrap.mlockall: true
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts:  ["es-tst-m01:9300","es-tst-m02:9300","es-tst-m03:9300"]
discovery.zen.fd.ping_timeout: 30s
node.master: true
node.data: false
node.client: false
action.disable_delete_all_indices: true
indices.cluster.send_refresh_mapping: false
index.refresh_interval: 60s
################################## Default Config Can be Overwritten  ###############
cluster.routing.allocation.cluster_concurrent_rebalance: 2
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.high: .95
cluster.routing.allocation.disk.watermark.low: .90
cluster.routing.allocation.node_concurrent_recoveries: 4
cluster.routing.allocation.node_initial_primaries_recoveries: 10
discovery.zen.minimum_master_nodes: 2
gateway.recover_after_data_nodes: 2
gateway.recover_after_master_nodes: 2
gateway.recover_after_time: 1m
http.max_content_length: 100mb
http.port: 9200
indices.fielddata.cache.size: 25%
indices.memory.index_buffer_size: 50%
indices.store.throttle.max_bytes_per_sec: 200mb
network.host: 0.0.0.0
threadpool.bulk.queue_size: 5000
threadpool.index.queue_size: 5000
######### Marvel settings if used #############
marvel.agent.exporters:
  d1:
     type: "http"
     host:  ["http://es-thr-mon2-m01:9200","http://es-thr-mon2-m01:9200"]
script.engine.groovy.inline.aggs: true
searchguard.ssl.transport.keystore_filepath: node-0-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false

**Comment by floragunncom** [comment]
On the machine where you generated the certificates which OpenSSL and Java version do you have installed?
You can find it out with the following command: <pre>openssl version</pre>
If you use openJDK keytool pls. try with Oracle Java keytool.

If you need valid test certificates look here: https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle

**Comment by ajaybhatnagar** [comment]
java version "1.8.0_92" (oracle Java, no Open JDK)
OS: 3.16.0-71-lowlatency (Ubuntu 14.04 Trusty)
OpenSSL 1.0.1f 6 Jan 2014

**Comment by ajaybhatnagar** [comment]
java version "1.8.0_92" (oracle Java, no Open JDK)
OS: 3.16.0-71-lowlatency (Ubuntu 14.04 Trusty)
OpenSSL 1.0.1f 6 Jan 2014

**Comment by ajaybhatnagar** [comment]
Found the the cause of invalid key file. It was file transfer issue with key files. However now startup throws this error:
[2016-07-07 15:46:28,062][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Not yet initialized
[2016-07-07 15:46:29,444][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Not yet initialized

And cluster health check reports:
 curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
Search Guard not initialized (SG11)

**Comment by floragunncom** [comment]
you to run sgadmin first

**Comment by ajaybhatnagar** [comment]
Did not find any instructions for running sgadmin in the documentation.  With my guess , when starting on one node it gives following error. Am I missing some info to run sgadmin ?

root@es-tst-m01:/usr/local/elasticsearch/plugins/search-guard-2/tools# ./sgadmin.sh  -ts /es1/etc/elasticsearch//truststore.jks -ks /es1/etc/elasticsearch/node-0-keystore.jks
Connect to localhost:9300
[17:31:49,640][WARN ] org.elasticsearch.client.transport - [Zero] node {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
ERR: Cannot connect to elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)

**Comment by floragunncom** [comment]
Especially see the <pre>-icl</pre> and <pre>-cn</pre> option

**Comment by floragunncom** [comment]
Will close this. If its not solved for you pls. ask question on google groups https://groups.google.com/forum/#!forum/search-guard or create an issue here: https://github.com/floragunncom/search-guard-ssl
